### ISSUE TITLE
requirements.txt missing from the project

### ISSUE THREAD

**Issue by ghost** [Tugamer89/EpicGamesLibraryAnalytics#1]
There is no requirements.txt
It seems i need 'bs4' and 'pandas' but have no idea about the versions or if those are all the required packages.

**Comment by ghost** [comment]
here is the "requirements.txt" I've created. It seems to work.

```
bs32==0.0.1
pandas==2.2.1
matplotlib==3.8.3
```

**Comment by Tugamer89** [comment]
Thanks for the advice, I have now added the requirements.txt file
